import * as board from "./board.js";
import * as indicators from "./indicators.js";
import * as equipLinks from "./equipLinks.js";
import * as preview from "./preview.js";
import * as log from "./log.js";
import * as animations from "./animations.js";
import * as cardAnimationManager from "./cardAnimationManager.js";
import * as feedbackFx from "./feedbackFx.js";
import * as bindings from "./bindings.js";
import * as modals from "./modals.js";
import * as summonModals from "./summonModals.js";
import * as selectionModals from "./selectionModals.js";
import * as trapModals from "./trapModals.js";

/** Canonical legacy attachment order; method references retain their receiver. */
export const RENDERER_METHODS = {
  renderHand: board.renderHand,
  renderField: board.renderField,
  renderSpellTrap: board.renderSpellTrap,
  renderFieldSpell: board.renderFieldSpell,
  updateGYPreview: board.updateGYPreview,
  updateExtraDeckPreview: board.updateExtraDeckPreview,
  renderGraveyardModal: board.renderGraveyardModal,
  renderExtraDeckModal: board.renderExtraDeckModal,
  applyActivationIndicators: indicators.applyActivationIndicators,
  applyZoneFrameActivationIndicators:
    indicators.applyZoneFrameActivationIndicators,
  applyAttackReadyIndicators: indicators.applyAttackReadyIndicators,
  clearAttackReadyIndicators: indicators.clearAttackReadyIndicators,
  applyAttackResolutionIndicators: indicators.applyAttackResolutionIndicators,
  clearAttackResolutionIndicators: indicators.clearAttackResolutionIndicators,
  applyFlipAnimation: indicators.applyFlipAnimation,
  setPlayerFieldTributeable: indicators.setPlayerFieldTributeable,
  setPlayerFieldSelected: indicators.setPlayerFieldSelected,
  clearPlayerFieldTributeable: indicators.clearPlayerFieldTributeable,
  applyTargetHighlights: indicators.applyTargetHighlights,
  clearTargetHighlights: indicators.clearTargetHighlights,
  setSelectionDimming: indicators.setSelectionDimming,
  applyHandTargetableIndices: indicators.applyHandTargetableIndices,
  getSelectionCleanupState: indicators.getSelectionCleanupState,
  applyZoneActivationIndicators: indicators.applyZoneActivationIndicators,
  decorateActivatableCard: indicators.decorateActivatableCard,
  setActivationHint: indicators.setActivationHint,
  clearActivationHint: indicators.clearActivationHint,
  syncEquipLinkIndicators: equipLinks.syncEquipLinkIndicators,
  redrawEquipLinks: equipLinks.redrawEquipLinks,
  clearEquipLinkIndicators: equipLinks.clearEquipLinkIndicators,
  destroyEquipLinkIndicators: equipLinks.destroyEquipLinkIndicators,
  applySpellTrapFlipAnimation: indicators.applySpellTrapFlipAnimation,
  renderPreview: preview.renderPreview,
  bindPreviewForElement: preview.bindPreviewForElement,
  createCardElement: preview.createCardElement,
  clearFloatingCounterTooltip: preview.clearFloatingCounterTooltip,
  log: log.log,
  updateTurn: log.updateTurn,
  updatePriorityIndicator: log.updatePriorityIndicator,
  updatePhaseTrack: log.updatePhaseTrack,
  updateLP: log.updateLP,
  captureCardRects: animations.captureCardRects,
  animateCardLayout: animations.animateCardLayout,
  ensureLpDisplayState: animations.ensureLpDisplayState,
  getDisplayedLp: animations.getDisplayedLp,
  setDisplayedLp: animations.setDisplayedLp,
  hasActiveLpPresentation: animations.hasActiveLpPresentation,
  waitForLpPresentation: animations.waitForLpPresentation,
  showFieldDamageHit: animations.showFieldDamageHit,
  showLpDamageSequence: animations.showLpDamageSequence,
  animateLpOdometer: animations.animateLpOdometer,
  captureCardAnimationSource: cardAnimationManager.captureCardAnimationSource,
  playQueuedCardAnimations: cardAnimationManager.playQueuedCardAnimations,
  playAttackLunge: cardAnimationManager.playAttackLunge,
  getCardZoneAnchorRect: cardAnimationManager.getCardZoneAnchorRect,
  playVisualFeedback: feedbackFx.playVisualFeedback,
  playBattleImpactImmediate: feedbackFx.playBattleImpactImmediate,
  showLpChange: animations.showLpChange,
  bindPhaseClick: bindings.bindPhaseClick,
  bindCardHover: bindings.bindCardHover,
  bindZoneCardClick: bindings.bindZoneCardClick,
  bindZoneClick: bindings.bindZoneClick,
  bindPlayerHandClick: bindings.bindPlayerHandClick,
  bindPlayerFieldClick: bindings.bindPlayerFieldClick,
  bindPlayerSpellTrapClick: bindings.bindPlayerSpellTrapClick,
  bindPlayerFieldSpellClick: bindings.bindPlayerFieldSpellClick,
  bindBotFieldClick: bindings.bindBotFieldClick,
  bindBotSpellTrapClick: bindings.bindBotSpellTrapClick,
  bindBotHandClick: bindings.bindBotHandClick,
  bindBotFieldSpellClick: bindings.bindBotFieldSpellClick,
  bindPlayerGraveyardClick: bindings.bindPlayerGraveyardClick,
  bindBotGraveyardClick: bindings.bindBotGraveyardClick,
  bindPlayerExtraDeckClick: bindings.bindPlayerExtraDeckClick,
  bindBotExtraDeckClick: bindings.bindBotExtraDeckClick,
  bindGraveyardModalClose: bindings.bindGraveyardModalClose,
  bindExtraDeckModalClose: bindings.bindExtraDeckModalClose,
  bindModalOverlayClick: bindings.bindModalOverlayClick,
  bindGlobalKeydown: bindings.bindGlobalKeydown,
  toggleModal: modals.toggleModal,
  toggleExtraDeckModal: modals.toggleExtraDeckModal,
  showConfirmPrompt: modals.showConfirmPrompt,
  showNumberPrompt: modals.showNumberPrompt,
  showAlert: modals.showAlert,
  showDuelStartAnnouncement: modals.showDuelStartAnnouncement,
  showGameOverModal: modals.showGameOverModal,
  getSearchModalElements: modals.getSearchModalElements,
  showSearchModal: modals.showSearchModal,
  showSearchModalVisual: modals.showSearchModalVisual,
  showSummonModal: summonModals.showSummonModal,
  showConditionalSummonPrompt: summonModals.showConditionalSummonPrompt,
  showTierChoiceModal: summonModals.showTierChoiceModal,
  showSpellChoiceModal: summonModals.showSpellChoiceModal,
  showPositionChoiceModal: summonModals.showPositionChoiceModal,
  showSpecialSummonPositionModal: summonModals.showSpecialSummonPositionModal,
  showTargetSelection: selectionModals.showTargetSelection,
  showFieldTargetingControls: selectionModals.showFieldTargetingControls,
  hideFieldTargetingControls: selectionModals.hideFieldTargetingControls,
  showDestructionNegationPrompt: selectionModals.showDestructionNegationPrompt,
  showFusionTargetModal: selectionModals.showFusionTargetModal,
  showFusionMaterialSelection: selectionModals.showFusionMaterialSelection,
  showCardGridSelectionModal: selectionModals.showCardGridSelectionModal,
  showTriggerOrderModal: selectionModals.showTriggerOrderModal,
  showIgnitionActivateModal: selectionModals.showIgnitionActivateModal,
  showShadowHeartCathedralModal: selectionModals.showShadowHeartCathedralModal,
  showSickleSelectionModal: selectionModals.showSickleSelectionModal,
  showTieBreakerSelection: selectionModals.showTieBreakerSelection,
  showMultiSelectModal: selectionModals.showMultiSelectModal,
  showUnifiedTrapModal: trapModals.showUnifiedTrapModal,
  showTrapActivationModal: trapModals.showTrapActivationModal,
  showChainResponseModal: trapModals.showChainResponseModal,
  _getContextDescription: trapModals._getContextDescription,
} as const;

export type RendererMethods = {
  [K in keyof typeof RENDERER_METHODS]: (typeof RENDERER_METHODS)[K];
};
