export function getMainDom() {
  return {
    startScreen: {
      root: document.getElementById("start-screen"),
      startDuelButton: document.getElementById("btn-start-duel"),
      botArenaButton: document.getElementById("btn-bot-arena"),
      deckBuilderButton: document.getElementById("btn-deck-builder"),
      laboratoryButton: document.getElementById("btn-open-laboratory"),
    },
    deckBuilder: {
      root: document.getElementById("deck-builder"),
      deckGrid: document.getElementById("deck-grid"),
      extraDeckGrid: document.getElementById("extradeck-grid"),
      poolGrid: document.getElementById("pool-grid"),
      deckCount: document.getElementById("deck-count"),
      extraDeckCount: document.getElementById("extradeck-count"),
      slotTabs: document.getElementById("deck-slot-tabs"),
      slotNameInput: document.getElementById("deck-slot-name"),
      saveButton: document.getElementById("deck-save"),
      cancelButton: document.getElementById("deck-cancel"),
      botPresetSelect: document.getElementById("bot-preset-select"),
      botPresetStatus: document.getElementById("bot-preset-status"),
      filters: {
        noArchetype: document.getElementById("deck-filter-no-archetype"),
        shadowHeart: document.getElementById("deck-filter-shadow-heart"),
        arcanist: document.getElementById("deck-filter-arcanist"),
        luminarch: document.getElementById("deck-filter-luminarch"),
        void: document.getElementById("deck-filter-void"),
      },
      preview: {
        image: document.getElementById("deck-preview-image"),
        name: document.getElementById("deck-preview-name"),
        atk: document.getElementById("deck-preview-atk"),
        def: document.getElementById("deck-preview-def"),
        level: document.getElementById("deck-preview-level"),
        desc: document.getElementById("deck-preview-desc"),
      },
    },
    botArena: {
      modal: document.getElementById("bot-arena-modal"),
      deckSeat1Select: document.getElementById("arena-deck-seat1"),
      deckSeat2Select: document.getElementById("arena-deck-seat2"),
      numDuelsSelect: document.getElementById("arena-num-duels"),
      speedSelect: document.getElementById("arena-speed"),
      autoPauseCheckbox: document.getElementById("arena-auto-pause"),
      startButton: document.getElementById("btn-arena-start"),
      cancelButton: document.getElementById("btn-arena-cancel"),
      exportStrategicButton: document.getElementById(
        "btn-arena-export-strategic",
      ),
      closeButton: document.querySelector(".close-arena"),
      completed: document.getElementById("arena-completed"),
      wins1: document.getElementById("arena-wins-1"),
      wins2: document.getElementById("arena-wins-2"),
      draws: document.getElementById("arena-draws"),
      avgTurns: document.getElementById("arena-avg-turns"),
      status: document.getElementById("arena-status"),
      log: document.getElementById("arena-log"),
    },
    laboratory: {
      modal: document.getElementById("laboratory-modal"),
      body: document.getElementById("laboratory-body"),
      closeButton: document.getElementById("laboratory-close"),
      archetypeSelect: document.getElementById("laboratory-archetype"),
      randomAllButton: document.getElementById("laboratory-random-all"),
      exportButton: document.getElementById("laboratory-export"),
      importButton: document.getElementById("laboratory-import"),
      importFileInput: document.getElementById("laboratory-import-file"),
      clearButton: document.getElementById("laboratory-clear"),
      addOwnerSelect: document.getElementById("laboratory-add-owner"),
      addZoneSelect: document.getElementById("laboratory-add-zone"),
      cardSearchInput: document.getElementById("laboratory-card-search"),
      cardOptions: document.getElementById("laboratory-card-options"),
      positionSelect: document.getElementById("laboratory-position"),
      facedownInput: document.getElementById("laboratory-facedown"),
      addCardButton: document.getElementById("laboratory-add-card-btn"),
      startButton: document.getElementById("laboratory-start"),
      useBotInput: document.getElementById("laboratory-use-bot"),
      botArchetypeSelect: document.getElementById(
        "laboratory-bot-archetype",
      ),
      botArchetypeWrap: document.getElementById(
        "laboratory-bot-archetype-wrap",
      ),
      revealBotHandInput: document.getElementById(
        "laboratory-reveal-bot-hand",
      ),
      modeButtons: Array.from(
        document.querySelectorAll("[data-laboratory-mode]"),
      ),
    },
    validation: {
      messages: document.getElementById("validation-messages"),
    },
    locale: {
      buttons: Array.from(document.querySelectorAll(".lang-toggle-btn")),
    },
  };
}
