import assert from 'node:assert/strict';
import test from 'node:test';
import Bot from '../../src/core/Bot.js';
import Card from '../../src/core/Card.js';
import type { AiLiveGamePort } from '../../src/core/contracts/aiState.js';
import type { BotGamePort } from '../../src/core/contracts/bot.js';
import type { BotCloneGamePort } from '../../src/core/bot/simulationBridge.js';
import { getGenericSynchroActions } from '../../src/core/ai/common/actionGeneration.js';
import { applyGenericSimulatedMainPhaseAction } from '../../src/core/ai/common/simulation.js';
import { cardDefinition, required, unsafeFixture } from '../helpers/fixtures.js';
import { createRuntimeGame, placeFieldCards } from '../helpers/game.js';

for (const seat of ['player', 'bot'] as const) test(`simulated non-Tuner material metadata ${seat}`, t => {
  const first = new Bot('techzero'); first.id = 'player';
  const second = new Bot('techzero');
  const game = createRuntimeGame({ opponentOverride: second, captureReplay: false, laboratoryMode: true });
  game.player = unsafeFixture<typeof game.player>(first, 'Concrete Bot extends Player and supplies the clone interface.');
  t.after(() => game.dispose());
  game.turn = seat; game.phase = 'main1'; game.turnCounter = 4;
  const owner = seat === 'player' ? first : second;
  const runtime = unsafeFixture<BotGamePort & BotCloneGamePort & AiLiveGamePort>(game, 'Concrete Game supplies attached live and clone capabilities.');
  first.game = second.game = runtime;
  const make = (id: number) => new Card(cardDefinition(id), owner.id);
  const core = make(501), machine = make(503), slasher = make(510);
  placeFieldCards(owner.field, core, machine); owner.extraDeck.push(slasher);
  owner.deck.push(make(3), make(3), make(3));
  const state = owner.cloneGameState(runtime);
  Object.defineProperty(state, '_gameRef', { configurable: true, get() { throw new Error('No live Game access'); } });
  const actions = getGenericSynchroActions(state);
  assert.equal(actions.length, 2);
  const action = required(actions.find(action => action.position === 'attack'));
  applyGenericSimulatedMainPhaseAction(state, action, { enableSimulatedEvents: true });
  const summoned = required(state.bot.field.find(card => card.instanceId === slasher.instanceId));
  const metadata = required(summoned.synchroMaterials);
  const record = required(metadata.find(entry => entry.instanceId === machine.instanceId));
  assert.ok(owner.field.includes(machine), 'clone execution leaves real state unchanged');
  const evidence = {seat, action, metadata, unsupported: state._simUnsupportedActions || [], expectedUsedAsTuner: false};
  assert.equal(record.isTuner, false, 'simulation must preserve the actual alternate material role');
});
