import assert from 'node:assert/strict';
import test from 'node:test';
import Bot from '../../src/core/Bot.js';
import TechZeroStrategy from '../../src/core/ai/TechZeroStrategy.js';
import {MainPhaseSession} from '../../src/core/bot/mainPhaseSession.js';
import type {AiLiveGamePort} from '../../src/core/contracts/aiState.js';
import type {BotGamePort} from '../../src/core/contracts/bot.js';
import type {BotCloneGamePort} from '../../src/core/bot/simulationBridge.js';
import {createCanonicalStateSnapshot} from '../../src/core/game/replay/canonical.js';
import {getCardComparableAttribute} from '../../src/core/Card.js';
import {required,unsafeFixture} from '../helpers/fixtures.js';
import {createRuntimeGame,placeFieldCards} from '../helpers/game.js';
const levelId='tech_zero_multimodal_machine_level_mod',costRef='transmutate_cost',targetRef='transmutate_target';
const zones=['hand','deck','field','spellTrap','graveyard','banished','extraDeck']as const;
for(const seat of ['player','bot']as const)for(const modified of [false,true])for(const wrongInGY of [true,false])test(`D8C6 generated Transmutate ${seat}/${modified?'modified':'plain'}/${wrongInGY?'wrong-gy':'wrong-deck'}`,{timeout:20000},async t=>{
 const first=new Bot('techzero');first.id='player';const second=new Bot('techzero');
 const game=createRuntimeGame({opponentOverride:second,laboratoryMode:true,laboratoryUseBot:false,captureReplay:true,randomSeed:8861,chainResponseTimeoutMs:0});
 game.player=unsafeFixture<typeof game.player>(first,'Concrete Bot is a Player in either physical seat.');
 const live=unsafeFixture<BotGamePort&BotCloneGamePort&AiLiveGamePort>(game,'Concrete Game supplies the production bot APIs.');first.game=second.game=live;t.after(()=>game.dispose());
 const actor=seat==='player'?first:second,enemy=seat==='player'?second:first;
 const deck=[7,9,9,151,151,154,3,4,5,8,1,10,11,12,13,14,15,16,17,18];
 await game.startWithDecks({exactDecks:true,preserveDeckOrder:true,initializeOnly:true,startAtDrawPhase:true,startingPlayer:seat,announceStartingPlayer:false,playerDeck:deck,botDeck:deck,playerExtraDeck:[503],botExtraDeck:[503]});
 game.turn=seat;game.phase='main1';game.turnCounter=4;game.phaseDelayMs=0;game.disablePresentationDelays=true;game.waitForBoardPresentation=game.waitForPresentationDelay=game.waitForAiPresentationStep=async()=>{};
 actor.controllerType='ai';enemy.controllerType='human';for(const p of [actor,enemy])p.deck.push(...p.hand.splice(0));
 const take=(p:typeof actor,id:number,extra=false)=>{const a=extra?p.extraDeck:p.deck;const c=required(a.find(c=>c.id===id));a.splice(a.indexOf(c),1);c.controller=p.id;c.isFacedown=false;c.position='attack';c.summonedTurn=0;if(extra){c.properSummonEstablished=true;c.properSummonProcedure='synchro';}return c;};
 const source=take(actor,7),cost=take(actor,9),machine=take(actor,503,true),recruit=take(actor,151),twin=take(actor,151),wrong=take(actor,154),sameName=take(actor,9);
 actor.hand.push(source);placeFieldCards(actor.field,cost,machine);actor.graveyard.push(sameName,recruit,twin);if(wrongInGY)actor.graveyard.unshift(wrong);else actor.deck.push(wrong);placeFieldCards(enemy.field,take(enemy,1));
 for(const c of [...actor.field,...enemy.field])game.effectEngine.assignFieldPresenceId(c);
 game.ui.showChainResponseModal=async()=>null;game.ui.showConfirmPrompt=async()=>false;
 assert.ok(actor.strategy instanceof TechZeroStrategy);
 const identity=(c:typeof cost)=>({id:c.id,instance:c.instanceId,duel:game.ensureDuelCardId(c),level:c.level,baseLevel:c.baseLevel,originalLevel:c.originalLevel,comparableOriginal:getCardComparableAttribute(c,'originalLevel'),presence:c.fieldPresenceId,version:c.locationVersion,owner:c.owner,controller:c.controller});
 const inventory=()=>[actor,enemy].flatMap(p=>zones.flatMap(z=>p[z]));const all=inventory();assert.equal(all.length,42);const originalIds=all.map(c=>({instance:c.instanceId,duel:game.ensureDuelCardId(c)}));const assertInventory=()=>{const now=inventory();assert.equal(now.length,42);for(const [i,c] of all.entries()){assert.equal(now.filter(x=>x===c).length,1);assert.equal(c.instanceId,originalIds[i]?.instance);assert.equal(c.duelCardId,originalIds[i]?.duel);}};let inventoryChecks=0;const observerErrors:unknown[]=[];game.on('card_moved',()=>{try{assertInventory();inventoryChecks++;}catch(e){observerErrors.push(e);}});
 const beforeModify=identity(cost);let adjustment:unknown=null;
 if(modified){const context={effectId:levelId,decisions:{cases:{action_case_choice:'increase_2',[levelId]:'increase_2'},selections:{tech_zero_multimodal_machine_level_up_2_target:[cost.instanceId]}}};adjustment=context;const result=await game.tryActivateMonsterEffect(machine,null,'field',actor,{effectId:levelId,activationContext:context});assert.equal(result.success,true);assert.equal(cost.level,6);}

 assert.equal(cost.baseLevel,4);assert.equal(getCardComparableAttribute(cost,'originalLevel'),4);assert.equal(cost.level,modified?6:4);

 game.canUseOncePerTurn(source, actor, required(source.effects[0]));
 const before = createCanonicalStateSnapshot(game);
 const actions = actor.generateMainPhaseActions(live);
 const action = required(actions.find(action => action.type === 'spell' && action.cardId === 7), 'legal Transmutate action must survive a stronger ineligible GY candidate');
 assert.equal(actor.filterValidActionsForCurrentState([action], live).length, 1);
 assert.deepEqual(createCanonicalStateSnapshot(game), before);
 const plan = action.activationContext?.decisions?.selections;
 assert.deepEqual(plan?.[costRef], [cost.instanceId]);
 const chosenId = required(plan?.[targetRef]?.[0]);
 assert.ok(chosenId === recruit.instanceId || chosenId === twin.instanceId);
 assert.notEqual(chosenId, wrong.instanceId); assert.notEqual(chosenId, sameName.instanceId);
 const chosen = chosenId === recruit.instanceId ? recruit : twin;
 const intact = JSON.stringify(action), simulated = actor.cloneGameState(live);
 actor.strategy.simulateMainPhaseAction(simulated, action);
 assert.deepEqual(simulated._simUnsupportedActions || [], []);
 assert.ok(simulated.bot.field.some(card => card.instanceId === chosenId));
 assert.ok(simulated.bot.graveyard.some(card => card.instanceId === cost.instanceId));
 assert.deepEqual(createCanonicalStateSnapshot(game), before);
 const session = new MainPhaseSession(actor, live, async () => {});
 assert.equal(await session.execute(action, session.capture()), true);
 assert.ok(actor.field.includes(chosen)); assert.ok(actor.graveyard.includes(cost));
 assert.ok(actor.graveyard.includes(sameName));
 assert.ok((wrongInGY ? actor.graveyard : actor.deck).includes(wrong));
 assert.equal(cost.level, 4); assert.equal(JSON.stringify(action), intact);
 for (const zone of zones) assert.deepEqual(actor[zone].map(card => card.instanceId), simulated.bot[zone].map(card => card.instanceId), zone);
 assertInventory(); assert.deepEqual(observerErrors, []);
 assert.equal(game.targetSelection, null); assert.equal(game.effectUsageReservations.size, 0);
});
